services:
  i18n:
    image: node:18-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./dist:/app/dist
    environment:
      PORT: 3000
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_SCHEMA: i18n
      DATABASE_URL: 'mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?schema=public'
      JWT_SECRET: MTxZGet65NgK1c1dj26LYO5OQVX6BPwK

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: i18n
volumes:
  todo-mysql-data:
